import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import CartProvider from '@/context/CartProvider';
import { Footer } from '@/components/Footer';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode; }>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <CartProvider>
      <section className="page">
        <main className="page-content">
          {children}
        </main>
        <Footer />
      </section>
    </CartProvider>
    </body>
    </html>
  );
}
